server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index pn-junction-simulator.html;

    location / {
        try_files $uri $uri/ /pn-junction-simulator.html;
    }
}
